services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: my-next-app
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: my-django-app
    ports:
      - "8000:8000"
    depends_on:
      - frontend